version: "3.8"
services:
  db:
    image: mysql/mysql-server
    container_name: imysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql314159
    ports:
    - 3306:3306
    volumes:
      - /mydata/mysql/data/db:/var/lib/mysql #数据文件挂载
      - /mydata/mysql/data/conf:/etc/mysql/conf.d #配置文件挂载
      - /mydata/mysql/log:/var/log/mysql #日志文件挂载

  redis:
    image: redis
    container_name: imongo
    volumes:
    - /mydata/redis/data:/data #数据文件挂载
    ports:
    - 6379:6379
  mongo:
    image: mongo
    container_name: imongo
    volumes:
      - /mydata/mongo/db:/data/db #数据文件挂载
    ports:
      - 27017:27017